# Taskfile.yml
# https://taskfile.dev

version: '3'

tasks:
  build:
    desc: Build the vanara binary into ./build
    cmds:
      - mkdir -p ./build
      - go build -o ./build/vanara ./cmd/vanara

  run:
    desc: Run the compiled vanara binary
    deps: [build]
    cmds:
      - ./build/vanara

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf ./build

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  test:lexer:
    desc: Run lexer package tests
    cmds:
      - go test -v ./pkg/lexer

  test:ast:
    desc: Run ast package tests
    cmds:
      - go test -v ./pkg/ast

  test:parser:
    desc: Run parser package tests
    cmds:
      - go test -v ./pkg/parser
